#!/usr/bin/env python3
"""Regenerate trim-forge/textures.js from a Minecraft client jar.

The previewer renders the game's own armour and trim textures, so the art has
to come out of a copy of the game. Point this at a client jar you already have:

    python3 tools/extract-textures.py \
        ~/Library/Application\\ Support/minecraft/versions/26.2/26.2.jar

Textures are inlined as data URIs rather than shipped as loose files, so the
page works when opened straight off disk — canvas pixel reads (needed for the
trim palette swap) are blocked for file:// images otherwise.
"""
import base64, json, pathlib, sys, zipfile

TEX = 'assets/minecraft/textures/'
PATTERNS = ['bolt', 'coast', 'dune', 'eye', 'flow', 'host', 'raiser', 'rib',
            'sentry', 'shaper', 'silence', 'snout', 'spire', 'tide', 'vex',
            'ward', 'wayfinder', 'wild']
PALETTES = ['trim_palette', 'amethyst', 'copper', 'copper_darker', 'diamond',
            'diamond_darker', 'emerald', 'gold', 'gold_darker', 'iron',
            'iron_darker', 'lapis', 'netherite', 'netherite_darker', 'quartz',
            'redstone', 'resin']
ARMOR = ['leather', 'leather_overlay', 'chainmail', 'copper', 'iron', 'gold',
         'diamond', 'netherite']
HELMET_ONLY = ['turtle_scute']


def main(jar_path):
    wanted = {}
    for p in PATTERNS:
        wanted[f'trims/humanoid/{p}'] = f'{TEX}trims/entity/humanoid/{p}.png'
        wanted[f'trims/leggings/{p}'] = f'{TEX}trims/entity/humanoid_leggings/{p}.png'
    for p in PALETTES:
        wanted[f'palettes/{p}'] = f'{TEX}trims/color_palettes/{p}.png'
    for a in ARMOR:
        wanted[f'armor/humanoid/{a}'] = f'{TEX}entity/equipment/humanoid/{a}.png'
        wanted[f'armor/leggings/{a}'] = f'{TEX}entity/equipment/humanoid_leggings/{a}.png'
    for a in HELMET_ONLY:
        wanted[f'armor/humanoid/{a}'] = f'{TEX}entity/equipment/humanoid/{a}.png'
    wanted['player/steve'] = f'{TEX}entity/player/wide/steve.png'

    out, total = {}, 0
    with zipfile.ZipFile(jar_path) as jar:
        names = set(jar.namelist())
        for key, path in sorted(wanted.items()):
            if path not in names:
                print(f'  missing: {path}', file=sys.stderr)
                continue
            blob = jar.read(path)
            total += len(blob)
            out[key] = 'data:image/png;base64,' + base64.b64encode(blob).decode()

    dest = pathlib.Path(__file__).resolve().parent.parent / 'textures.js'
    with dest.open('w') as fh:
        fh.write('/* Generated by tools/extract-textures.py — do not edit by hand.\n')
        fh.write(f'   Source: {pathlib.Path(jar_path).name}\n')
        fh.write('   Armour, trim and player textures are (c) Mojang Studios, inlined\n')
        fh.write('   as data URIs so the page works from file://. */\n\n')
        fh.write('const TEXTURES = {\n')
        for key in sorted(out):
            fh.write(f'  {json.dumps(key)}: {json.dumps(out[key])},\n')
        fh.write('};\n')
    print(f'wrote {dest} — {len(out)} textures, {total} bytes of PNG')


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
