server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /Games/dark-tunnels/ {
        alias /usr/share/nginx/html/;
        add_header Cross-Origin-Opener-Policy "same-origin";
        add_header Cross-Origin-Embedder-Policy "require-corp";
        try_files $uri $uri/ =404;
    }

    location / {
        return 301 /Games/dark-tunnels/;
    }
}
